import './base.scss';
import { storyblokInit, apiPlugin } from '@storyblok/react/rsc';
import StoryblokProvider from '@/context/StoryblokProvider';
import App from '@/components/app/App';

storyblokInit({
  accessToken: process.env.storyblokApiToken,
  use: [apiPlugin],
  apiOptions: {
    region: 'us',
  },
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <StoryblokProvider>
      <html lang="en">
        {/* <meta /> */}
        {/* <head> */}
        <body>
          <App>{children}</App>
        </body>
      </html>
    </StoryblokProvider>
  );
}
